'use strict';

module.exports = {
    AED: { prefix: '\u062c' },
    ANG: { prefix: '\u0192' },
    ARS: { prefix: '$', suffix: ' ARS' },
    AUD: { prefix: '$', suffix: ' AUD' },
    AWG: { prefix: '\u0192' },
    BBD: { prefix: '$', suffix: ' BBD' },
    BGN: { prefix: '\u043b\u0432' },
    BTC: { suffix: ' BTC', precision: 4 },
    BMD: { prefix: '$', suffix: ' BMD' },
    BND: { prefix: '$', suffix: ' BND' },
    BRL: { prefix: 'R$' },
    BSD: { prefix: '$', suffix: ' BSD' },
    CAD: { prefix: '$', suffix: ' CAD' },
    CHF: { suffix: ' CHF' },
    CLP: { prefix: '$', suffix: ' CLP' },
    CNY: { prefix: '\u00A5' },
    COP: { prefix: '$', suffix: ' COP' },
    CRC: { prefix: '\u20A1' },
    CZK: { prefix: 'Kc' },
    DKK: { prefix: 'kr' },
    DOP: { prefix: '$', suffix: ' DOP' },
    EEK: { prefix: 'kr' },
    EUR: { prefix: '\u20AC' },
    GBP: { prefix: '\u00A3' },
    GTQ: { prefix: 'Q' },
    HKD: { prefix: '$', suffix: ' HKD' },
    HRK: { prefix: 'kn' },
    HUF: { prefix: 'Ft' },
    IDR: { prefix: 'Rp' },
    ILS: { prefix: '\u20AA' },
    INR: { prefix: 'Rs.' },
    ISK: { prefix: 'kr' },
    JMD: { prefix: 'J$' },
    JPY: { prefix: '\u00A5', precision: 0 },
    KRW: { prefix: '\u20A9' },
    KYD: { prefix: '$', suffix: ' KYD' },
    LTL: { prefix: 'Lt' },
    LVL: { prefix: 'Ls' },
    MXN: { prefix: '$', suffix: ' MXN' },
    MYR: { prefix: 'RM' },
    NOK: { prefix: 'kr' },
    NZD: { prefix: '$', suffix: ' NZD' },
    PEN: { prefix: 'S/' },
    PHP: { prefix: 'Php' },
    PLN: { prefix: 'z' },
    QAR: { prefix: '\ufdfc' },
    RON: { prefix: 'lei' },
    RUB: { prefix: '\u0440\u0443\u0431' },
    SAR: { prefix: '\ufdfc' },
    SEK: { prefix: 'kr' },
    SGD: { prefix: '$', suffix: ' SGD' },
    THB: { prefix: '\u0E3F' },
    TRY: { prefix: 'TL' },
    TTD: { prefix: 'TT$' },
    TWD: { prefix: 'NT$' },
    UAH: { prefix: '\u20b4' },
    USD: { prefix: '$' },
    UYU: { prefix: '$U' },
    VEF: { prefix: 'Bs' },
    VND: { prefix: '\u20ab' },
    XCD: { prefix: '$', suffix: ' XCD' },
    ZAR: { prefix: 'R' }
};
